---
title: "Correlación"
author: "Sara Aponte, Juan Roa y Juan Guayazán"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r importDataset}
library(readr)
icfes_20201 <- read_csv("icfes_20201.csv")
library(ggplot2)
vars_puntajes <- c(
  "PUNT_LECTURA_CRITICA",
  "PUNT_MATEMATICAS",
  "PUNT_C_NATURALES",
  "PUNT_SOCIALES_CIUDADANAS",
  "PUNT_INGLES",
  "PUNT_GLOBAL"
)
library(corrplot)

```

```{r , factor}
### Estrato
icfes_20201$FAMI_ESTRATOVIVIENDA <- factor(
  icfes_20201$FAMI_ESTRATOVIVIENDA,
  levels = c("Estrato 1","Estrato 2","Estrato 3","Estrato 4","Estrato 5","Estrato 6","Sin Estrato"),
  ordered = TRUE
)

### Educación Padre
icfes_20201$FAMI_EDUCACIONPADRE <- factor(
  icfes_20201$FAMI_EDUCACIONPADRE,
  levels = c(
    "Ninguno",
    "Primaria incompleta",
    "Primaria completa",
    "Secundaria (Bachillerato) incompleta",
    "Secundaria (Bachillerato) completa",
    "Técnica o tecnológica incompleta",
    "Técnica o tecnológica completa",
    "Educación profesional incompleta",
    "Educación profesional completa",
    "Postgrado",
    "No sabe",
    "No Aplica"
  ),
  ordered = TRUE
)

### Educación Madre
icfes_20201$FAMI_EDUCACIONMADRE <- factor(
  icfes_20201$FAMI_EDUCACIONMADRE,
  levels = c(
    "Ninguno",
    "Primaria incompleta",
    "Primaria completa",
    "Secundaria (Bachillerato) incompleta",
    "Secundaria (Bachillerato) completa",
    "Técnica o tecnológica incompleta",
    "Técnica o tecnológica completa",
    "Educación profesional incompleta",
    "Educación profesional completa",
    "Postgrado",
    "No sabe",
    "No Aplica"
  ),
  ordered = TRUE
)

### Lectura diaria
icfes_20201$ESTU_DEDICACIONLECTURADIARIA <- factor(
  icfes_20201$ESTU_DEDICACIONLECTURADIARIA,
  levels = c(
    "No leo por entretenimiento",
    "30 minutos o menos",
    "Entre 30 y 60 minutos",
    "Entre 1 y 2 horas",
    "Más de 2 horas"
  ),
  ordered = TRUE
)

### Horas semanales trabajadas
icfes_20201$ESTU_HORASSEMANATRABAJA <- factor(
  icfes_20201$ESTU_HORASSEMANATRABAJA,
  levels = c(
    "0",
    "Menos de 10 horas",
    "Entre 11 y 20 horas",
    "Entre 21 y 30 horas",
    "Más de 30 horas"
  ),
  ordered = TRUE
)

### Número de libros
icfes_20201$FAMI_NUMLIBROS <- factor(
  icfes_20201$FAMI_NUMLIBROS,
  levels = c(
    "0 A 10 LIBROS",
    "11 A 25 LIBROS",
    "26 A 100 LIBROS",
    "MÁS DE 100 LIBROS"
  ),
  ordered = TRUE
)

### Frecuencia: leche
icfes_20201$FAMI_COMELECHEDERIVADOS <- factor(
  icfes_20201$FAMI_COMELECHEDERIVADOS,
  levels = c(
    "Todos o casi todos los días",
    "3 a 5 veces por semana",
    "1 o 2 veces por semana",
    "Nunca o rara vez comemos eso"
  ),
  ordered = TRUE
)

### Frecuencia: carne/pescado/huevo
icfes_20201$FAMI_COMECARNEPESCADOHUEVO <- factor(
  icfes_20201$FAMI_COMECARNEPESCADOHUEVO,
  levels = c(
    "Todos o casi todos los días",
    "3 a 5 veces por semana",
    "1 o 2 veces por semana",
    "Nunca o rara vez comemos eso"
  ),
  ordered = TRUE
)

### Frecuencia: cereales/frutas/legumbres
icfes_20201$FAMI_COMECEREALFRUTOSLEGUMBRE <- factor(
  icfes_20201$FAMI_COMECEREALFRUTOSLEGUMBRE,
  levels = c(
    "Todos o casi todos los días",
    "3 a 5 veces por semana",
    "1 o 2 veces por semana",
    "Nunca o rara vez comemos eso"
  ),
  ordered = TRUE
)
```

```{r , eliminarNA}
icfes_corr <- icfes_20201[, c(
  "PUNT_LECTURA_CRITICA",
  "PUNT_MATEMATICAS",
  "PUNT_C_NATURALES",
  "PUNT_SOCIALES_CIUDADANAS",
  "PUNT_INGLES",
  "PUNT_GLOBAL",
  "FAMI_ESTRATOVIVIENDA",
  "FAMI_EDUCACIONPADRE",
  "FAMI_EDUCACIONMADRE",
  "ESTU_DEDICACIONLECTURADIARIA",
  "ESTU_HORASSEMANATRABAJA",
  "FAMI_NUMLIBROS",
  "FAMI_COMELECHEDERIVADOS",
  "FAMI_COMECARNEPESCADOHUEVO",
  "FAMI_COMECEREALFRUTOSLEGUMBRE"
)]
icfes_corr <- na.omit(icfes_corr)
icfes_corr[, vars_puntajes] <- lapply(
  icfes_corr[, vars_puntajes],
  function(x) as.numeric(as.character(x))
)


```

```{r , matrizCorrelacion}
cor_pearson <- cor(icfes_corr[, vars_puntajes], method = "pearson")
cor_pearson
```

```{r , MatrizSpearman}
vars_ordinales_num <- sapply(icfes_corr[, c(
  "FAMI_ESTRATOVIVIENDA",
  "FAMI_EDUCACIONPADRE",
  "FAMI_EDUCACIONMADRE",
  "ESTU_DEDICACIONLECTURADIARIA",
  "ESTU_HORASSEMANATRABAJA",
  "FAMI_NUMLIBROS",
  "FAMI_COMELECHEDERIVADOS",
  "FAMI_COMECARNEPESCADOHUEVO",
  "FAMI_COMECEREALFRUTOSLEGUMBRE"
)], as.numeric)
```

```{r}
cor_spearman <- cor(vars_ordinales_num, method = "spearman")
cor_spearman
```

```{r , MatrizKendall}
cor_kendall <- cor(vars_ordinales_num, method = "kendall")
cor_kendall

```

```{r , cambio}
# ---- Renombrar variables para la visualización ----

# Nombres bonitos para puntajes
nombres_puntajes <- c(
  "Lectura Crítica",
  "Matemáticas",
  "C. Naturales",
  "Sociales",
  "Inglés",
  "Global"
)

# Renombrar Pearson
colnames(cor_pearson) <- nombres_puntajes
rownames(cor_pearson) <- nombres_puntajes

# Nombres bonitos para ordinales
nombres_ordinales <- c(
  "Estrato",
  "Edu. Padre",
  "Edu. Madre",
  "Lectura Diario",
  "Horas Trabajo",
  "Libros",
  "Leche",
  "Carne/Huevo",
  "Cereales"
)

# Renombrar Spearman
colnames(cor_spearman) <- nombres_ordinales
rownames(cor_spearman) <- nombres_ordinales

# Renombrar Kendall
colnames(cor_kendall) <- nombres_ordinales
rownames(cor_kendall) <- nombres_ordinales
```

```{r , HeatmapCorrelaciones}
corrplot(cor_pearson, method = "color", na.label = " ")
corrplot(cor_spearman, method = "color", na.label = " ")
corrplot(cor_kendall, method = "color", na.label = " ")
```

```{r , echo=TRUE}

```